<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-NM6NUFVG" failures="1" tests="9" name="com.mycompany.app.AppTest" time="0.022" errors="0" timestamp="2022-04-22T18:23:46 IST" skipped="5">
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.002">
    <skipped/>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.001">
    <skipped/>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.001">
    <skipped/>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithTrue" time="0.003"/>
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="AnswerWithFalse" time="0.008"/>
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.000">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.mycompany.app.AppTest.shouldAnswerWithFalse(AppTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.002">
    <skipped/>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="AnswerWithTrue" time="0.003"/>
  <system-out/>
  <testcase classname="com.mycompany.app.AppTest" name="shouldAnswerWithFalse" time="0.002">
    <skipped/>
  </testcase> <!-- shouldAnswerWithFalse -->
  <system-out/>
</testsuite> <!-- com.mycompany.app.AppTest -->
